# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.23.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.23.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kist/Downloads/PSI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kist/Downloads/PSI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.23.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.23.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kist/Downloads/PSI/CMakeFiles /Users/kist/Downloads/PSI//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kist/Downloads/PSI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PSI

# Build rule for target.
PSI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PSI
.PHONY : PSI

# fast build rule for target.
PSI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/build
.PHONY : PSI/fast

#=============================================================================
# Target rules for targets named PSI_autogen

# Build rule for target.
PSI_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PSI_autogen
.PHONY : PSI_autogen

# fast build rule for target.
PSI_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI_autogen.dir/build.make CMakeFiles/PSI_autogen.dir/build
.PHONY : PSI_autogen/fast

PSI_autogen/EWIEGA46WW/qrc_icon.o: PSI_autogen/EWIEGA46WW/qrc_icon.cpp.o
.PHONY : PSI_autogen/EWIEGA46WW/qrc_icon.o

# target to build an object file
PSI_autogen/EWIEGA46WW/qrc_icon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/PSI_autogen/EWIEGA46WW/qrc_icon.cpp.o
.PHONY : PSI_autogen/EWIEGA46WW/qrc_icon.cpp.o

PSI_autogen/EWIEGA46WW/qrc_icon.i: PSI_autogen/EWIEGA46WW/qrc_icon.cpp.i
.PHONY : PSI_autogen/EWIEGA46WW/qrc_icon.i

# target to preprocess a source file
PSI_autogen/EWIEGA46WW/qrc_icon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/PSI_autogen/EWIEGA46WW/qrc_icon.cpp.i
.PHONY : PSI_autogen/EWIEGA46WW/qrc_icon.cpp.i

PSI_autogen/EWIEGA46WW/qrc_icon.s: PSI_autogen/EWIEGA46WW/qrc_icon.cpp.s
.PHONY : PSI_autogen/EWIEGA46WW/qrc_icon.s

# target to generate assembly for a file
PSI_autogen/EWIEGA46WW/qrc_icon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/PSI_autogen/EWIEGA46WW/qrc_icon.cpp.s
.PHONY : PSI_autogen/EWIEGA46WW/qrc_icon.cpp.s

PSI_autogen/mocs_compilation.o: PSI_autogen/mocs_compilation.cpp.o
.PHONY : PSI_autogen/mocs_compilation.o

# target to build an object file
PSI_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/PSI_autogen/mocs_compilation.cpp.o
.PHONY : PSI_autogen/mocs_compilation.cpp.o

PSI_autogen/mocs_compilation.i: PSI_autogen/mocs_compilation.cpp.i
.PHONY : PSI_autogen/mocs_compilation.i

# target to preprocess a source file
PSI_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/PSI_autogen/mocs_compilation.cpp.i
.PHONY : PSI_autogen/mocs_compilation.cpp.i

PSI_autogen/mocs_compilation.s: PSI_autogen/mocs_compilation.cpp.s
.PHONY : PSI_autogen/mocs_compilation.s

# target to generate assembly for a file
PSI_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/PSI_autogen/mocs_compilation.cpp.s
.PHONY : PSI_autogen/mocs_compilation.cpp.s

functionkey.o: functionkey.cpp.o
.PHONY : functionkey.o

# target to build an object file
functionkey.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/functionkey.cpp.o
.PHONY : functionkey.cpp.o

functionkey.i: functionkey.cpp.i
.PHONY : functionkey.i

# target to preprocess a source file
functionkey.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/functionkey.cpp.i
.PHONY : functionkey.cpp.i

functionkey.s: functionkey.cpp.s
.PHONY : functionkey.s

# target to generate assembly for a file
functionkey.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/functionkey.cpp.s
.PHONY : functionkey.cpp.s

logtext.o: logtext.cpp.o
.PHONY : logtext.o

# target to build an object file
logtext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/logtext.cpp.o
.PHONY : logtext.cpp.o

logtext.i: logtext.cpp.i
.PHONY : logtext.i

# target to preprocess a source file
logtext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/logtext.cpp.i
.PHONY : logtext.cpp.i

logtext.s: logtext.cpp.s
.PHONY : logtext.s

# target to generate assembly for a file
logtext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/logtext.cpp.s
.PHONY : logtext.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/main.cpp.s
.PHONY : main.cpp.s

mainscreen.o: mainscreen.cpp.o
.PHONY : mainscreen.o

# target to build an object file
mainscreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/mainscreen.cpp.o
.PHONY : mainscreen.cpp.o

mainscreen.i: mainscreen.cpp.i
.PHONY : mainscreen.i

# target to preprocess a source file
mainscreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/mainscreen.cpp.i
.PHONY : mainscreen.cpp.i

mainscreen.s: mainscreen.cpp.s
.PHONY : mainscreen.s

# target to generate assembly for a file
mainscreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/mainscreen.cpp.s
.PHONY : mainscreen.cpp.s

stage.o: stage.cpp.o
.PHONY : stage.o

# target to build an object file
stage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/stage.cpp.o
.PHONY : stage.cpp.o

stage.i: stage.cpp.i
.PHONY : stage.i

# target to preprocess a source file
stage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/stage.cpp.i
.PHONY : stage.cpp.i

stage.s: stage.cpp.s
.PHONY : stage.s

# target to generate assembly for a file
stage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/stage.cpp.s
.PHONY : stage.cpp.s

startpsi.o: startpsi.cpp.o
.PHONY : startpsi.o

# target to build an object file
startpsi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/startpsi.cpp.o
.PHONY : startpsi.cpp.o

startpsi.i: startpsi.cpp.i
.PHONY : startpsi.i

# target to preprocess a source file
startpsi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/startpsi.cpp.i
.PHONY : startpsi.cpp.i

startpsi.s: startpsi.cpp.s
.PHONY : startpsi.s

# target to generate assembly for a file
startpsi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/startpsi.cpp.s
.PHONY : startpsi.cpp.s

state_variable.o: state_variable.cpp.o
.PHONY : state_variable.o

# target to build an object file
state_variable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/state_variable.cpp.o
.PHONY : state_variable.cpp.o

state_variable.i: state_variable.cpp.i
.PHONY : state_variable.i

# target to preprocess a source file
state_variable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/state_variable.cpp.i
.PHONY : state_variable.cpp.i

state_variable.s: state_variable.cpp.s
.PHONY : state_variable.s

# target to generate assembly for a file
state_variable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/state_variable.cpp.s
.PHONY : state_variable.cpp.s

subscreen.o: subscreen.cpp.o
.PHONY : subscreen.o

# target to build an object file
subscreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/subscreen.cpp.o
.PHONY : subscreen.cpp.o

subscreen.i: subscreen.cpp.i
.PHONY : subscreen.i

# target to preprocess a source file
subscreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/subscreen.cpp.i
.PHONY : subscreen.cpp.i

subscreen.s: subscreen.cpp.s
.PHONY : subscreen.s

# target to generate assembly for a file
subscreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/subscreen.cpp.s
.PHONY : subscreen.cpp.s

widgetcontrolpanel.o: widgetcontrolpanel.cpp.o
.PHONY : widgetcontrolpanel.o

# target to build an object file
widgetcontrolpanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetcontrolpanel.cpp.o
.PHONY : widgetcontrolpanel.cpp.o

widgetcontrolpanel.i: widgetcontrolpanel.cpp.i
.PHONY : widgetcontrolpanel.i

# target to preprocess a source file
widgetcontrolpanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetcontrolpanel.cpp.i
.PHONY : widgetcontrolpanel.cpp.i

widgetcontrolpanel.s: widgetcontrolpanel.cpp.s
.PHONY : widgetcontrolpanel.s

# target to generate assembly for a file
widgetcontrolpanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetcontrolpanel.cpp.s
.PHONY : widgetcontrolpanel.cpp.s

widgetcurrentposition.o: widgetcurrentposition.cpp.o
.PHONY : widgetcurrentposition.o

# target to build an object file
widgetcurrentposition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetcurrentposition.cpp.o
.PHONY : widgetcurrentposition.cpp.o

widgetcurrentposition.i: widgetcurrentposition.cpp.i
.PHONY : widgetcurrentposition.i

# target to preprocess a source file
widgetcurrentposition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetcurrentposition.cpp.i
.PHONY : widgetcurrentposition.cpp.i

widgetcurrentposition.s: widgetcurrentposition.cpp.s
.PHONY : widgetcurrentposition.s

# target to generate assembly for a file
widgetcurrentposition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetcurrentposition.cpp.s
.PHONY : widgetcurrentposition.cpp.s

widgetdirectchange.o: widgetdirectchange.cpp.o
.PHONY : widgetdirectchange.o

# target to build an object file
widgetdirectchange.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetdirectchange.cpp.o
.PHONY : widgetdirectchange.cpp.o

widgetdirectchange.i: widgetdirectchange.cpp.i
.PHONY : widgetdirectchange.i

# target to preprocess a source file
widgetdirectchange.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetdirectchange.cpp.i
.PHONY : widgetdirectchange.cpp.i

widgetdirectchange.s: widgetdirectchange.cpp.s
.PHONY : widgetdirectchange.s

# target to generate assembly for a file
widgetdirectchange.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetdirectchange.cpp.s
.PHONY : widgetdirectchange.cpp.s

widgetmenupanel.o: widgetmenupanel.cpp.o
.PHONY : widgetmenupanel.o

# target to build an object file
widgetmenupanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetmenupanel.cpp.o
.PHONY : widgetmenupanel.cpp.o

widgetmenupanel.i: widgetmenupanel.cpp.i
.PHONY : widgetmenupanel.i

# target to preprocess a source file
widgetmenupanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetmenupanel.cpp.i
.PHONY : widgetmenupanel.cpp.i

widgetmenupanel.s: widgetmenupanel.cpp.s
.PHONY : widgetmenupanel.s

# target to generate assembly for a file
widgetmenupanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetmenupanel.cpp.s
.PHONY : widgetmenupanel.cpp.s

widgetsection.o: widgetsection.cpp.o
.PHONY : widgetsection.o

# target to build an object file
widgetsection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetsection.cpp.o
.PHONY : widgetsection.cpp.o

widgetsection.i: widgetsection.cpp.i
.PHONY : widgetsection.i

# target to preprocess a source file
widgetsection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetsection.cpp.i
.PHONY : widgetsection.cpp.i

widgetsection.s: widgetsection.cpp.s
.PHONY : widgetsection.s

# target to generate assembly for a file
widgetsection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PSI.dir/build.make CMakeFiles/PSI.dir/widgetsection.cpp.s
.PHONY : widgetsection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PSI_autogen"
	@echo "... PSI"
	@echo "... PSI_autogen/EWIEGA46WW/qrc_icon.o"
	@echo "... PSI_autogen/EWIEGA46WW/qrc_icon.i"
	@echo "... PSI_autogen/EWIEGA46WW/qrc_icon.s"
	@echo "... PSI_autogen/mocs_compilation.o"
	@echo "... PSI_autogen/mocs_compilation.i"
	@echo "... PSI_autogen/mocs_compilation.s"
	@echo "... functionkey.o"
	@echo "... functionkey.i"
	@echo "... functionkey.s"
	@echo "... logtext.o"
	@echo "... logtext.i"
	@echo "... logtext.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainscreen.o"
	@echo "... mainscreen.i"
	@echo "... mainscreen.s"
	@echo "... stage.o"
	@echo "... stage.i"
	@echo "... stage.s"
	@echo "... startpsi.o"
	@echo "... startpsi.i"
	@echo "... startpsi.s"
	@echo "... state_variable.o"
	@echo "... state_variable.i"
	@echo "... state_variable.s"
	@echo "... subscreen.o"
	@echo "... subscreen.i"
	@echo "... subscreen.s"
	@echo "... widgetcontrolpanel.o"
	@echo "... widgetcontrolpanel.i"
	@echo "... widgetcontrolpanel.s"
	@echo "... widgetcurrentposition.o"
	@echo "... widgetcurrentposition.i"
	@echo "... widgetcurrentposition.s"
	@echo "... widgetdirectchange.o"
	@echo "... widgetdirectchange.i"
	@echo "... widgetdirectchange.s"
	@echo "... widgetmenupanel.o"
	@echo "... widgetmenupanel.i"
	@echo "... widgetmenupanel.s"
	@echo "... widgetsection.o"
	@echo "... widgetsection.i"
	@echo "... widgetsection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

